application: moztw-tasks
version: dog
runtime: python
api_version: 1

handlers:
## Favion url.
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  mime_type: image/x-icon

## Images files.
- url: /images
  static_dir: static/images
- url: /images/(.*)
  static_files: static/images/\1
  upload: static/images/(.*)

## Site map xml.
- url: /sitemap\.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml

## CSS
- url: /css
  static_dir: static/css
- url: /css/(.*)
  static_files: static/css/\1
  upload: static/css/(.*)

## Mail
- url: /_ah/mail/.+ 
  #script: handle_incoming_email.py
  script: mail.py
  login: admin

## Mailbox
- url: /mailtoall
  script: main.py
  secure: always
  login: admin

## Chart
- url: /chart
  script: main.py
  secure: always
  login: admin

## perding
- url: /gorand
  script: gorand.py
  secure: always
  login: admin

## Cron
- url: /cron
  script: cronsendmail.py
  #secure: always
  login: admin

## Main WSGI
- url: .*
  script: main.py
  secure: always
  #login: admin

inbound_services:
- mail
